<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit60bd92a4c6de479686a91a424976ced9
{
    public static $prefixLengthsPsr4 = array (
        'D' => 
        array (
            'Dokumd\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Dokumd\\' => 
        array (
            0 => __DIR__ . '/../..' . '/Dokumd',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit60bd92a4c6de479686a91a424976ced9::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit60bd92a4c6de479686a91a424976ced9::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit60bd92a4c6de479686a91a424976ced9::$classMap;

        }, null, ClassLoader::class);
    }
}
